services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: nginx:web-server
    container_name: concierge-web-server
    depends_on:
      - server
    ports:
      - 8081:80
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    networks:
      - local-concierge

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: node:app-server
    volumes:
      - ./server:/usr/src/app
    container_name: concierge-app-server
    tty: true
    # server/.envを作成し以下を設定してもOK
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - db
    networks:
      - local-concierge
    working_dir: /usr/src/app
    command: [sh, -c, npm install && npm run dev]

  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      # - ./db/conf:/etc/mysql/conf.d/:ro
    networks:
      - local-concierge
volumes:
  mysql:

networks:
  local-concierge: